import type {Metadata} from "next";
import "./globals.css";
import {AuthProvider} from "@/context/authContext";
import {TooltipProvider} from "@/components/ui/tooltip";
import "../global.css";
import {ProfileProvider} from "@/context/profileContext";
import React from "react";
import {GroupProvider} from "@/context/groupContext";

export const metadata: Metadata = {
    title: "Tsundoku",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body>
        <AuthProvider>
            <ProfileProvider>
                <GroupProvider>
                    <TooltipProvider>
                        {children}
                    </TooltipProvider>
                </GroupProvider>
            </ProfileProvider>
        </AuthProvider>
        </body>
        </html>
    );
}
