import type {Metadata} from "next";
import "./globals.css";
import {AuthProvider} from "@/context/authContext";
import {TooltipProvider} from "@/components/ui/tooltip";

export const metadata: Metadata = {
    title: "Tsundoku",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className="bg-primary-black">
        <AuthProvider>
                <TooltipProvider>
                    {children}
                </TooltipProvider>
        </AuthProvider>
        </body>
        </html>
    );
}
